using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace AutoUserGenerator;

[Generator]
public class AutoUserGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForPostInitialization(ctx =>
        {
            const string attributeSource = """
                                           // <auto-generated />
                                           using System;

                                           [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
                                           internal sealed class AutoUserAttribute : Attribute { }
                                           """;

            ctx.AddSource("AutoUserAttribute.g.cs",
                SourceText.From(attributeSource, Encoding.UTF8));
        });
    }

    public void Execute(GeneratorExecutionContext context)
    {
        const string source = """
                              // <auto-generated />
                              using System;

                              public partial class User
                              {
                                  public partial User(string name)
                                  {
                                      Name = name;
                                      OnNameChanged(name);
                                  }

                                  private event Action<string>? _nameChanged;

                                  public partial event Action<string> NameChanged
                                  {
                                      add    { _nameChanged += value; }
                                      remove { _nameChanged -= value; }
                                  }

                                  private void OnNameChanged(string newName)
                                  {
                                      _nameChanged?.Invoke(newName);
                                  }

                                  public partial void Rename(string newName)
                                  {
                                      Name = newName;
                                      OnNameChanged(newName);
                                  }
                              }
                              """;

        context.AddSource("AutoUser.g.cs", SourceText.From(source, Encoding.UTF8));
    }
}